"""Add PO and Invoice

Revision ID: 4d3aa7d01a97
Revises: d8a5c808a2f2
Create Date: 2026-06-06 11:05:17.783959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3aa7d01a97'
down_revision = 'd8a5c808a2f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('rfq_id', sa.String(length=36), nullable=True),
    sa.Column('vendor_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('po_id', sa.String(length=36), nullable=True),
    sa.Column('vendor_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('rfq_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('vendor_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=True)

    with op.batch_alter_table('rfq_items', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('rfq_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=True)

    with op.batch_alter_table('rfqs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('vendor_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=True)

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('vendor_id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('rfqs', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('rfq_items', schema=None) as batch_op:
        batch_op.alter_column('rfq_id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.alter_column('vendor_id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('rfq_id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.drop_table('invoices')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
